-- Hayden Hoopes
-- Lab 3

-- Problem 1
SELECT TRAVEL_ID, TO_CHAR(TRAVEL_START_TIME, 'MON DD, YYYY')
FROM InstantRide.Travels
WHERE travel_start_time 
    BETWEEN TO_DATE('01-10-2019', 'DD-MM-YYYY') AND TO_DATE('02-10-2019', 'DD-MM-YYYY');
    
-- Problem 2
SELECT D.DRIVER_FIRST_NAME, 
        D.DRIVER_LAST_NAME, 
        D.DRIVER_DRIVING_LICENSE_ID, 
        T.TRAVEL_START_TIME, 
        T.TRAVEL_END_TIME
FROM INSTANTRIDE.DRIVERS D
    LEFT JOIN INSTANTRIDE.TRAVELS T ON D.DRIVER_ID = T.DRIVER_ID
;

-- Problem 3
SELECT U.USER_FIRST_NAME, 
    U.USER_LAST_NAME, 
    T.TRAVEL_START_TIME, 
    T.TRAVEL_END_TIME
FROM INSTANTRIDE.USERS U
    JOIN INSTANTRIDE.TRAVELS T USING (USER_ID)
;

-- Problem 4
SELECT T.TRAVEL_ID, 
    D.DRIVER_FIRST_NAME, 
    D.DRIVER_LAST_NAME, 
    T.TRAVEL_PRICE, 
    T.TRAVEL_DISCOUNT
FROM INSTANTRIDE.TRAVELS T
    JOIN INSTANTRIDE.DRIVERS D ON T.DRIVER_ID = D.DRIVER_ID
;

-- Problem 5
SELECT DISTINCT U1.USER_FIRST_NAME, U1.USER_LAST_NAME
FROM INSTANTRIDE.USERS U1
    JOIN INSTANTRIDE.USERS U2 ON U1.USER_FIRST_NAME = U2.USER_FIRST_NAME
WHERE 
    U1.USER_FIRST_NAME = U2.USER_FIRST_NAME AND
    U1.USER_LAST_NAME = U2.USER_LAST_NAME AND
    U1.USER_ID <> U2.USER_ID
;

-- Problem 6
SELECT *
FROM INSTANTRIDE.TRAVELS T
WHERE T.DRIVER_ID IN
    (
        SELECT D.DRIVER_ID
        FROM INSTANTRIDE.DRIVERS D
        WHERE D.DRIVER_RATING < 4
    )
;
