/* -----
Lab 4
----- */

-- Problem 1
SELECT DRIVER_ID
    , CONCAT(FLOOR(DRIVER_RATING), '+') AS DRIVER_RATING_GROUP
FROM INSTANTRIDE.DRIVERS
WHERE DRIVER_RATING > 0
;

-- Problem 2
SELECT DRIVER_FIRST_NAME AS FIRST_NAME
    , DRIVER_LAST_NAME AS LAST_NAME
FROM INSTANTRIDE.DRIVERS
UNION 
SELECT USER_FIRST_NAME
    , USER_LAST_NAME
FROM INSTANTRIDE.USERS
;

-- Problem 3
SELECT DRIVER_FIRST_NAME || ' ' || DRIVER_LAST_NAME AS FULL_NAME
FROM INSTANTRIDE.DRIVERS
MINUS
SELECT USER_FIRST_NAME || ' ' || USER_LAST_NAME
FROM INSTANTRIDE.USERS
;

-- Problem 4
SELECT CAR_ID
    , ROUND(AVG(DISCOUNT_AMOUNT),2) AS AVERAGE_DISCOUNT
FROM 
        (SELECT CAR_ID, ROUND(TRAVEL_PRICE * TRAVEL_DISCOUNT, 2) AS DISCOUNT_AMOUNT
        FROM INSTANTRIDE.TRAVELS
        WHERE TRAVEL_DISCOUNT IS NOT NULL)
GROUP BY CAR_ID
;